FagweekendQ3/ViewModels/ArtistViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FagweekendQ3.ViewModels
{
    public class ArtistViewModel
    {
        public string Id { get; set; }
        [Required]
        [StringLength(50,MinimumLength = 5)]
        public string Name { get; set; }
    }
}

FagweekendQ3/Controllers/ArtistController.cs
using System.Linq;
using System.Web.Mvc;
using FagweekendQ3.DataStore;
using FagweekendQ3.ViewModels;

namespace FagweekendQ3.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistStore _artistStore;

        public ArtistController(IArtistStore artistStore)
        {
            _artistStore = artistStore;
        }

        public ActionResult Index()
        {
            var model = _artistStore.GetAll().Select(x => new ArtistViewModel {Id = x.Id, Name = x.Name});
            return View(model);
        }

        public ActionResult Edit(string id)
        {
            ArtistViewModel model;
            if(!string.IsNullOrWhiteSpace(id))
            {
                var artist = _artistStore.Get(id);
                model = new ArtistViewModel { Id = artist.Id, Name = artist.Name };
            }
            else
            {
                model = new ArtistViewModel();
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ArtistViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (!string.IsNullOrWhiteSpace(model.Id))
            {
                var artist = _artistStore.Get(model.Id);
                artist.ChangeName(model.Name);
            }
            else
            {
                _artistStore.Add(model.Name);
            }

            return RedirectToAction("Index");
        }
    }
}

FagweekendQ3/Views/Artist/Edit.cshtml
@using FagweekendQ3.ViewModels
@model ArtistViewModel
@{
    ViewBag.Title = "Edit artist";
}

<h2>Rediger @Model.Name</h2>
@Html.ValidationSummary()

@using(Html.BeginForm()){
    @Html.HiddenFor(x => x.Id)
    @Html.EditorFor(x => x.Name)
    @Html.ValidationMessageFor(x => x.Name)
    
    <br />
    <input type="submit" />
}

FagweekendQ3/Views/Artist/Index.cshtml
@using FagweekendQ3.ViewModels
@model IEnumerable<ArtistViewModel>
@{
    ViewBag.Title = "Home Page";
}

<h2>Artists</h2>
<div>
    <ul>
        @foreach( var artist in Model)
        {
            <li>@artist.Name - @Html.ActionLink("Rediger","Edit",new {artist.Id})</li>
        }
    </ul>
    @Html.ActionLink("Ny","Edit", new {Id = ""})
</div>

FagweekendQ3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.tmpl.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout-1.3.0beta.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout.mapping.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/date.js")" type="text/javascript"></script>
   
   
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                Username: @ViewBag.UserName
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Artister", "Index", "Artist")</li>
                    <li>@Html.ActionLink("Album", "Index", "Album")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

FagweekendQ3/Views/Track/Index.cshtml
@using FagweekendQ3.ViewModels
@model AddTrackViewModel
@{
    ViewBag.Title = "Add new track..";
}

<h2>Legg til nytt track til @Model.Name</h2>
@using(Html.BeginForm("New", "Track")){
    @Html.HiddenFor(x => x.AlbumId)
    @Html.EditorFor(x => x.TrackNo)
    @Html.EditorFor(x => x.Name)
    @Html.EditorFor(x => x.TrackLength)
    <input type="submit" />
}